### Upload sales uplaod 

POST http://localhost:3001/sales/upload
Content-Type: application/json

{
  "register": "657509efb0c5853ab661195e",
  "ofert": "1",
  "neigborhood": "1",
  "property": "1",
  "stratum": "1",
  "price": "1",
  "room": "1",
  "restroom": "1",
  "age": "1",
  "administration": "1",
  "area": "1",
  "description": "1",
  "picture": [
    {
      "fieldname": "carro",
      "originalname": "carro.jpg",
      "encoding": "base64",
      "mimetype": "image/jpeg"
    }
  ]
}



{
  "next": "",
  "previous": null,
  "result": [
    {
      "continent": "America",
      "country": [
        {
          "id": 1,
          "indicative": "+ 57",
          "currency": "COP",
          "name": "Colombia",
          "city": [
            {
              "id": 1,
              "name": "Bogotá",
            },
            {
              "id": 2,
              "name": "Medellin",
            },
            {
              "id": 3,
              "name": "Cali",
            },
            {
              "id": 4,
              "name": "Cartagena",
            },
            {
              "id": 5,
              "name": "Barranquilla",
            },
            {
              "id": 6,
              "name": "Bucaramanga",
            },
            {
              "id": 7,
              "name": "Cucuta",
            },
            {
              "id": 8,
              "name": "Pereira",
            }
          ]
        },
        {
          "id": 2,
          "indicative": "+ 55",
          "currency": "BRL",
          "name": "Brasil",
          "city": [
            {
              "id": 1,
              "name": "Sao pablo",
            },
            {
              "id": 2,
              "name": "Rio de janeiro",
            }
          ]
        },
        {
          "id": 3,
          "indicative": "+ 54",
          "currency": "ARS",
          "name": "Argentina",
          "city": [
            {
              "id": 1,
              "name": "Buenos Aires",
            },
            {
              "id": 2,
              "name": "Mendoza",
            }
          ]
        },
        {
          "id": 4,
          "indicative": "+ 56",
          "currency": "CLP",
          "name": "Chile",
          "city": [
            {
              "id": 1,
              "name": "Santiago de chile",
            },
            {
              "id": 2,
              "name": "Antofagasta",
            }
          ]
        },
        {
          "id": 5,
          "indicative": "+ 51",
          "currency": "PEN",
          "name": "Peru",
          "city": [
            {
              "id": 1,
              "name": "Santiago de chile",
            },
            {
              "id": 2,
              "name": "Antofagasta",
            }
          ]
        },
        {
          "id": 6,
          "indicative": "+ 593",
          "currency": "USD",
          "name": "ECUADOR",
          "city": [
            {
              "id": 1,
              "name": "Guayaquil",
            },
            {
              "id": 2,
              "name": "Quito",
            }
          ]
        },
        {
          "id": 6,
          "indicative": "+ 58",
          "currency": "USD",
          "name": "Venezuela",
          "city": [
            {
              "id": 1,
              "name": "Caracas",
            },
            {
              "id": 2,
              "name": "Maracaibo",
            }
          ]
        },
      ]
    }
  ]
}


